In [1]:
import pandas as pd
import numpy as np
table  = pd.read_csv('ds_salaries.csv')

In [2]:
table

Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT   
1             1       2020               SE              FT   
2             2       2020               SE              FT   
3             3       2020               MI              FT   
4             4       2020               SE              FT   
..          ...        ...              ...             ...   
602         602       2022               SE              FT   
603         603       2022               SE              FT   
604         604       2022               SE              FT   
605         605       2022               SE              FT   
606         606       2022               MI              FT   

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833   
1    Machine Learning Scientist  260000             USD         260000   
2             Big Data Engineer   85000             GBP         109024   
3          Product Data Analyst   20000             USD          20000   
4     Machine Learning Engineer  150000             USD         150000   
..                          ...     ...             ...            ...   
602               Data Engineer  154000             USD         154000   
603               Data Engineer  126000             USD         126000   
604                Data Analyst  129000             USD         129000   
605                Data Analyst  150000             USD         150000   
606                AI Scientist  200000             USD         200000   

    employee_residence  remote_ratio company_location company_size  
0                   DE             0               DE            L  
1                   JP             0               JP            S  
2                   GB            50               GB            M  
3                   HN             0               HN            S  
4                   US            50               US            L  
..                 ...           ...              ...          ...  
602                 US           100               US            M  
603                 US           100               US            M  
604                 US             0               US            M  
605                 US           100               US            M  
606                 IN           100               US            L  

[607 rows x 12 columns]

In [3]:
table.head()

Unnamed: 0  work_year experience_level employment_type  \
0           0       2020               MI              FT   
1           1       2020               SE              FT   
2           2       2020               SE              FT   
3           3       2020               MI              FT   
4           4       2020               SE              FT   

                    job_title  salary salary_currency  salary_in_usd  \
0              Data Scientist   70000             EUR          79833   
1  Machine Learning Scientist  260000             USD         260000   
2           Big Data Engineer   85000             GBP         109024   
3        Product Data Analyst   20000             USD          20000   
4   Machine Learning Engineer  150000             USD         150000   

  employee_residence  remote_ratio company_location company_size  
0                 DE             0               DE            L  
1                 JP             0               JP            S  
2                 GB            50               GB            M  
3                 HN             0               HN            S  
4                 US            50               US            L

In [4]:
table.tail()

Unnamed: 0  work_year experience_level employment_type      job_title  \
602         602       2022               SE              FT  Data Engineer   
603         603       2022               SE              FT  Data Engineer   
604         604       2022               SE              FT   Data Analyst   
605         605       2022               SE              FT   Data Analyst   
606         606       2022               MI              FT   AI Scientist   

     salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
602  154000             USD         154000                 US           100   
603  126000             USD         126000                 US           100   
604  129000             USD         129000                 US             0   
605  150000             USD         150000                 US           100   
606  200000             USD         200000                 IN           100   

    company_location company_size  
602               US            M  
603               US            M  
604               US            M  
605               US            M  
606               US            L

In [5]:
table.describe()

Unnamed: 0    work_year        salary  salary_in_usd  remote_ratio
count  607.000000   607.000000  6.070000e+02     607.000000     607.00000
mean   303.000000  2021.405272  3.240001e+05  112297.869852      70.92257
std    175.370085     0.692133  1.544357e+06   70957.259411      40.70913
min      0.000000  2020.000000  4.000000e+03    2859.000000       0.00000
25%    151.500000  2021.000000  7.000000e+04   62726.000000      50.00000
50%    303.000000  2022.000000  1.150000e+05  101570.000000     100.00000
75%    454.500000  2022.000000  1.650000e+05  150000.000000     100.00000
max    606.000000  2022.000000  3.040000e+07  600000.000000     100.00000

In [6]:
table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Unnamed: 0          607 non-null    int64 
 1   work_year           607 non-null    int64 
 2   experience_level    607 non-null    object
 3   employment_type     607 non-null    object
 4   job_title           607 non-null    object
 5   salary              607 non-null    int64 
 6   salary_currency     607 non-null    object
 7   salary_in_usd       607 non-null    int64 
 8   employee_residence  607 non-null    object
 9   remote_ratio        607 non-null    int64 
 10  company_location    607 non-null    object
 11  company_size        607 non-null    object
dtypes: int64(5), object(7)
memory usage: 40.4+ KB


In [7]:
table.columns

Index(['Unnamed: 0', 'work_year', 'experience_level', 'employment_type',
       'job_title', 'salary', 'salary_currency', 'salary_in_usd',
       'employee_residence', 'remote_ratio', 'company_location',
       'company_size'],
      dtype='object')

In [8]:
table.isnull().sum()

Unnamed: 0            0
work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [9]:
table.head()

Unnamed: 0  work_year experience_level employment_type  \
0           0       2020               MI              FT   
1           1       2020               SE              FT   
2           2       2020               SE              FT   
3           3       2020               MI              FT   
4           4       2020               SE              FT   

                    job_title  salary salary_currency  salary_in_usd  \
0              Data Scientist   70000             EUR          79833   
1  Machine Learning Scientist  260000             USD         260000   
2           Big Data Engineer   85000             GBP         109024   
3        Product Data Analyst   20000             USD          20000   
4   Machine Learning Engineer  150000             USD         150000   

  employee_residence  remote_ratio company_location company_size  
0                 DE             0               DE            L  
1                 JP             0               JP            S  
2                 GB            50               GB            M  
3                 HN             0               HN            S  
4                 US            50               US            L

In [11]:
import matplotlib.pyplot as plt
import seaborn as sns

<class 'ModuleNotFoundError'>: No module named 'seaborn'

In [167]:
ab = table.drop(columns=['Unnamed: 0', 'salary', 'salary_currency', 'employee_residence', 'remote_ratio', 'company_location']) 

In [168]:
ab

work_year  experience_level  employment_type  job_title  salary_in_usd  \
0         2020                 2                2         22          79833   
1         2020                 3                2         41         260000   
2         2020                 3                2          7         109024   
3         2020                 2                2         47          20000   
4         2020                 3                2         38         150000   
..         ...               ...              ...        ...            ...   
602       2022                 3                2         17         154000   
603       2022                 3                2         17         126000   
604       2022                 3                2         12         129000   
605       2022                 3                2         12         150000   
606       2022                 2                2          1         200000   

    company_size  
0              L  
1              S  
2              M  
3              S  
4              L  
..           ...  
602            M  
603            M  
604            M  
605            M  
606            L  

[607 rows x 6 columns]

In [169]:
ab['result'] = ab['salary_in_usd'].apply(lambda x:1 if x>100000 else 0)

In [170]:
ab

work_year  experience_level  employment_type  job_title  salary_in_usd  \
0         2020                 2                2         22          79833   
1         2020                 3                2         41         260000   
2         2020                 3                2          7         109024   
3         2020                 2                2         47          20000   
4         2020                 3                2         38         150000   
..         ...               ...              ...        ...            ...   
602       2022                 3                2         17         154000   
603       2022                 3                2         17         126000   
604       2022                 3                2         12         129000   
605       2022                 3                2         12         150000   
606       2022                 2                2          1         200000   

    company_size  result  
0              L       0  
1              S       1  
2              M       1  
3              S       0  
4              L       1  
..           ...     ...  
602            M       1  
603            M       1  
604            M       1  
605            M       1  
606            L       1  

[607 rows x 7 columns]

In [171]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ab['experience_level'] = le.fit_transform(ab['experience_level'])
ab['employment_type'] = le.fit_transform(ab['employment_type'])
ab['job_title'] = le.fit_transform(ab['job_title'])
ab['company_size'] = le.fit_transform(ab['company_size'])

In [202]:
a = ab[['experience_level', 'employment_type', 'job_title']].values

In [203]:
a

array([[ 2,  2, 22],
       [ 3,  2, 41],
       [ 3,  2,  7],
       ...,
       [ 3,  2, 12],
       [ 3,  2, 12],
       [ 2,  2,  1]])

In [204]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(a, ab.result.values, test_size=0.25, random_state=0)

In [205]:
x_train

array([[ 0,  2,  7],
       [ 2,  2, 12],
       [ 2,  2, 22],
       ...,
       [ 3,  2, 16],
       [ 2,  2,  7],
       [ 3,  2, 22]])

In [206]:
x_test

array([[ 3,  2, 22],
       [ 0,  2,  1],
       [ 2,  2, 12],
       [ 3,  2, 17],
       [ 3,  2, 46],
       [ 0,  3, 22],
       [ 3,  2, 17],
       [ 0,  2, 17],
       [ 3,  2, 38],
       [ 3,  2, 17],
       [ 3,  2, 12],
       [ 3,  2, 29],
       [ 2,  2, 22],
       [ 3,  2, 22],
       [ 3,  2, 20],
       [ 2,  2, 17],
       [ 3,  2, 12],
       [ 3,  2, 17],
       [ 0,  2, 17],
       [ 3,  2, 17],
       [ 2,  2, 22],
       [ 3,  2, 12],
       [ 2,  2, 17],
       [ 3,  2, 38],
       [ 1,  2, 19],
       [ 2,  2, 38],
       [ 2,  2, 22],
       [ 0,  2, 12],
       [ 2,  2, 38],
       [ 2,  2, 22],
       [ 3,  2, 17],
       [ 3,  2, 37],
       [ 0,  2, 38],
       [ 2,  2, 22],
       [ 2,  2, 12],
       [ 3,  2, 12],
       [ 3,  2, 12],
       [ 3,  2, 12],
       [ 2,  2, 17],
       [ 3,  2, 17],
       [ 2,  2, 17],
       [ 3,  2, 48],
       [ 2,  2, 12],
       [ 3,  2, 12],
       [ 3,  2, 12],
       [ 1,  2, 17],
       [ 2,  2, 12],
       [ 3,  

In [207]:
y_train

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,

In [208]:
y_test

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0],
      dtype=int64)

In [209]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
pre = dtc.fit(x_train, y_train)

In [210]:
y_pred = dtc.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0],
      dtype=int64)

In [211]:
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred)
cm

array([[58, 16],
       [16, 62]], dtype=int64)

In [212]:
acc = metrics.accuracy_score(y_test, y_pred)
acc

0.7894736842105263

In [213]:
pre = metrics.precision_score(y_test, y_pred)
pre

0.7948717948717948

In [214]:
re = metrics.recall_score(y_test, y_pred)
re

0.7948717948717948

In [215]:
f1 = metrics.f1_score(y_test, y_pred)
f1

0.7948717948717948

In [216]:
cr = metrics.classification_report(y_test, y_pred)
cr

'              precision    recall  f1-score   support\n\n           0       0.78      0.78      0.78        74\n           1       0.79      0.79      0.79        78\n\n    accuracy                           0.79       152\n   macro avg       0.79      0.79      0.79       152\nweighted avg       0.79      0.79      0.79       152\n'